### PR TITLE
Increase contrast and change colors on heatmap

### PR DESCRIPTION
**Pull request by nhick**
Lowered the midpoint of the scale to color lower values and changed scale to white->blue->red.
Addresess #4

### CODE REVIEW

**Comment by brendangregg** [comment]
No, thanks, this does not address #4. Please see the description I wrote in #4.

I would not make this the default as A) it increases the (already difficult) learning curve for newcomers, who must now learn a two-hue non-linear palette by default; and B) adding more hues becomes visually distracting for some profiles (it looks bad). I'd have this as an enhance button only (if you click enhance, it will now use two hues and be non-linear). I'd also seriously look at using blue only for counts 1 & 2, for reasons I explained in #4, unless there is a better reason than that.

**Comment by nhick** [comment]
Got it. Wasn't sure as to default and wanted to avoid adding any UI element. Will do so and update the PR.

**Comment by nhick** [comment]
Updated to meet all requirements set forth in #4

**Comment by brendangregg** [comment]
Thanks, however, this changes the default palette. I don't think it should. This new default palette is lighter, and heat maps appear a bit more washed out.

**Comment by nhick** [comment]
Yeah, was setting it to pure red and missed reverting it for the default palette. Changing now.

**Comment by brendangregg** [comment]
Did you test this? When I try, they are still very different.

Before:

screen shot 2018-04-10 at 7 05 51 am

After:

screen shot 2018-04-10 at 7 06 20 am

These should be exactly the same.

**Comment by nhick** [comment]
Odd. Yes, these should be the same. Let me check.

**Comment by nhick** [comment]
The midpoint of the color scale was removed by accident + pink was set at the upper bound. All is sorted in https://github.com/Netflix/flamescope/pull/20/commits/6f785903c22012756ef890a8c2f42a67bcd61033. Sorry for that.
Adapted the 'enhanced' scale to the default scale. When selected it will map colors as follows:
- _0_ white,
- _1-2_ within blue hue,
- _2-midpoint_ pink to mid-red,
- _midpoint-max_ mid-red to full-red.

**Comment by brendangregg** [comment]
I'll need to learn how to ```merge --squash```; What I normally do as a contributor is a ```git rebase -i HEAD~#``` to squash the commits and ```git push --force```. Which seems to work.

Yes, we can do follow on issues and PRs to extend this in the settings modal (do we even have that exposed yet?).

**Comment by spiermar** [comment]
Merged. Adjusting a few things shortly.

**Pull request merged**
