### PR TITLE
Add a note about c++filt

### PR DESCRIPTION
**Pull request by bobrik**
Converting this:

```
_ZN8tcmalloc15CentralFreeList11RemoveRangeEPPvS2_i
```

into this:

```
tcmalloc::CentralFreeList::RemoveRange(void**, void**, int)
```

### CODE REVIEW

**Comment by brendangregg** [comment]
I'm fine with the change, although I think perf sometimes does this automatically (or maybe I was dreaming).

**Comment by bobrik** [comment]
I was surprised to not find this detail in your notes on flamegraphs, maybe there's something wrong with our setup. We just use stock `perf` that comes with 4.14.

Our target runs in a Docker container, maybe it makes the difference.

**Comment by brendangregg** [comment]
Yeah, I've seen it not work too, but I haven't dug into why. Normally it does work for us. Just taking a quick look at the perf source, it does have:

```
Makefile.perf:# Define NO_DEMANGLE if you do not want C++ symbol demangling.
```

So your perf is probably built with NO_DEMANGLE, which is probably autodetected based on available libraries. Anyway. We should note the c++filt workaround in the comments.

**Comment by bobrik** [comment]
Relevant snippet:

* https://github.com/torvalds/linux/blob/71b8ebbf3d7b/tools/perf/Makefile.config#L707-L727

I added `libberty-dev` to the build dependencies and `perf` does demangle automatically.

Thanks for pointing in the right direction.

**Pull request merged**
